CREATE TABLE `packages` (
  `id` int NOT NULL AUTO_INCREMENT,
  `resi` varchar(50) NOT NULL,
  `sender_name` varchar(100) NOT NULL,
  `sender_phone` varchar(30) NOT NULL,
  `sender_address` text NOT NULL,
  `receiver_name` varchar(100) NOT NULL,
  `receiver_phone` varchar(30) NOT NULL,
  `receiver_address` text NOT NULL,
  `origin_branch_id` int NOT NULL,
  `destination_branch_id` int DEFAULT NULL,
  `weight` decimal(10,2) NOT NULL DEFAULT '1.00',
  `price` decimal(15,2) NOT NULL DEFAULT '0.00',
  `status` enum('PENDING','PICKUP','GUDANG_ASAL','TRANSIT','GUDANG_TUJUAN','DELIVERY','SELESAI','RETUR') NOT NULL DEFAULT 'PENDING',
  `created_by` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_resi` (`resi`),
  KEY `fk_packages_origin_branch` (`origin_branch_id`),
  KEY `fk_packages_dest_branch` (`destination_branch_id`),
  KEY `fk_packages_user` (`created_by`),
  CONSTRAINT `fk_packages_origin_branch` FOREIGN KEY (`origin_branch_id`) REFERENCES `branches` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_packages_dest_branch` FOREIGN KEY (`destination_branch_id`) REFERENCES `branches` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_packages_user` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `tracking_histories` (
  `id` int NOT NULL AUTO_INCREMENT,
  `package_id` int NOT NULL,
  `branch_id` int DEFAULT NULL,
  `user_id` int DEFAULT NULL,
  `status` varchar(50) NOT NULL,
  `description` text NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_tracking_package` (`package_id`),
  KEY `fk_tracking_branch` (`branch_id`),
  KEY `fk_tracking_user` (`user_id`),
  CONSTRAINT `fk_tracking_package` FOREIGN KEY (`package_id`) REFERENCES `packages` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_tracking_branch` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_tracking_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
